version: '3.8'

services:
  webapp:
    build: .
    ports:
      - "3019:3019"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/webtech
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: